provisions = {
    'default': {
        'short': {
            'food': 12,
            'torch': 8,
            'shovel': 2,
            'key': 0,
            'bandage': 0,
            'antivenom': 0,
            'medicinal_herbs': 0,
            'holy_water': 0,
        },
        'medium': {
            'food': 18,
            'torch': 13,
            'shovel': 3,
            'key': 0,
            'bandage': 0,
            'antivenom': 0,
            'medicinal_herbs': 0,
            'holy_water': 0,
        },
        'long': {
            'food': 24,
            'torch': 16,
            'shovel': 4,
            'key': 0,
            'bandage': 0,
            'antivenom': 0,
            'medicinal_herbs': 0,
            'holy_water': 0,
        }
    },
    'the_courtyard_modifiers' : {
        
    } ,

    'ruins_modifiers': {
        'short': {
            'food': 0,
            'torch': 0,
            'shovel': 0,
            'key': 1,
            'bandage': 1,
            'antivenom': 0,
            'medicinal_herbs': 1,
            'holy_water': 2,
        },
        'medium': {
            'food': 0,
            'torch': 0,
            'shovel': 0,
            'key': 2,
            'bandage': 2,
            'antivenom': 0,
            'medicinal_herbs': 2,
            'holy_water': 3,
        },
        'long': {
            'food': 0,
            'torch': 0,
            'shovel': 0,
            'key': 3,
            'bandage': 3,
            'antivenom': 0,
            'medicinal_herbs': 3,
            'holy_water': 4,
        }
    },

    'warrens_modifiers': {
        'short': {
            'food': 0,
            'torch': 2,
            'shovel': 0,
            'key': 2,
            'bandage': 1,
            'antivenom': 0,
            'medicinal_herbs': 3,
            'holy_water': 1,
        },
        'medium': {
            'food': 0,
            'torch': 3,
            'shovel': 0,
            'key': 3,
            'bandage': 2,
            'antivenom': 0,
            'medicinal_herbs': 4,
            'holy_water': 2,
        },
        'long': {
            'food': 0,
            'torch': 4,
            'shovel': 0,
            'key': 4,
            'bandage': 3,
            'antivenom': 0,
            'medicinal_herbs': 5,
            'holy_water': 3,
        },
    },

    'weald_modifiers': {
        'short': {
            'food': 0,
            'torch': 0,
            'shovel': 1,
            'key': 1,
            'bandage': 2,
            'antivenom': 2,
            'medicinal_herbs': 1,
            'holy_water': 1,
        },
        'medium': {
            'food': 0,
            'torch': 0,
            'shovel': 2,
            'key': 2,
            'bandage': 3,
            'antivenom': 3,
            'medicinal_herbs': 2,
            'holy_water': 2,
        },
        'long': {
            'food': 0,
            'torch': 0,
            'shovel': 0,
            'key': 3,
            'bandage': 3,
            'antivenom': 0,
            'medicinal_herbs': 3,
            'holy_water': 4,
        },
    },

    'cove_modifiers': {
        'short': {
            'food': 0,
            'torch': 0,
            'shovel': 1,
            'key': 1,
            'bandage': 2,
            'antivenom': 0,
            'medicinal_herbs': 2,
            'holy_water': 0,
        },
        'medium': {
            'food': 0,
            'torch': 0,
            'shovel': 2,
            'key': 2,
            'bandage': 4,
            'antivenom': 1,
            'medicinal_herbs': 3,
            'holy_water': 1,
        },
        'long': {
            'food': 0,
            'torch': 0,
            'shovel': 2,
            'key': 3,
            'bandage': 6,
            'antivenom': 1,
            'medicinal_herbs': 4,
            'holy_water': 1,
        },
    },

    'darkest_dungeon_modifiers': {
        'medium': {
            'food': 6,
            'torch': 11,
            'shovel': 2,
            'key': 2,
            'bandage': 4,
            'antivenom': 1,
            'medicinal_herbs': 3,
            'holy_water': 1,
        },
    },

    'farmstead_modifiers': {
        'medium': {
            'food': 6,
            'torch': None,
            'shovel': None,
            'key': 4,
            'bandage': 9,
            'antivenom': 9,
            'medicinal_herbs': 9,
            'holy_water': 9,
        },
    },
}
